import Link from "next/link";
import { Container } from "react-bootstrap";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Layout from "components/Layout";
import PageHero from "components/sd/PageHero";

export default function ConservationPage() {
  const { t } = useTranslation("common");
  const heroTitle = "Commerce can fund the planet.";
  const heroDescription = "Sustainable Discounts is a movement, not just a mechanism. Scientists, conservationists, activists, journalists, founders, celebrities, industry associations, sustainability experts. If you believe commerce can be redesigned to protect nature, there is a role for you here.";

  const problemCopy = {
    headline: "The funding crisis is structural. So is the solution.",
    body: "Nature needs $942 billion more per year than it currently receives. Governments are cutting. Corporate pledges disappear with earnings cycles. More than a quarter of conservation professionals are burning out. Not because they stopped caring. Because there is never enough money to do the work they know how to do. SD does not ask conservation to work harder. It brings a new source of money entirely."
  };

  const offerCopy = {
    headline: "Reliable, recurrent funding. Generated by commerce. Not by donors.",
    body: "Every SD transaction generates a verified conservation contribution. The funding scales with commerce. More brands, more transactions, more conservation. It does not depend on donor generosity, grant cycles, or government budgets. SD transfers 90% of all contributions to verified projects within 90 days. SD retains 10% for operations. Surplus goes back to conservation."
  };

  const whoItems = [
    "Conservation organizations. If a project is scientifically proven to deliver immediate, significant results, SD will fund it.",
    "Scientists and academics. Help us identify where every dollar creates the most immediate impact.",
    "Celebrities, activists, and public figures. A voice behind SD reaches the audiences that make movements real.",
    "Journalists. The story of commerce funding nature, at scale, has not been told yet.",
    "Industry associations. Your members are looking for immediate environmental impact. SD delivers it now, buying time for longer solutions.",
    "Sustainability experts. Durable goods industries are struggling to generate real results. SD solves that at the point of sale.",
    "Founders and investors. Building something that accelerates this movement? Talk to us.",
    "Philanthropists. Your giving goes further when it funds the mechanism, not just the projects.",
    "Activists. SD gives you a commercial tool that delivers change."
  ];

  const allocationCopy = {
    headline: "The Conservationist's Dream Team.",
    body: "SD's allocation decisions are governed by an independent committee, currently being assembled. Two co-equal primary criteria: Climate Velocity and Biodiversity Integrity. Climate Velocity: maximizing the speed and volume of carbon sequestration. Biodiversity Integrity: protecting the keystone species and ecosystems that sustain life. Secondary criteria: Scalability and Community Benefit. Every allocation decision will be published with full reasoning and data. We are seeking representation from leading scientific institutions and frontline conservation practitioners."
  };

  const industryCopy = {
    headline: "Your industries need immediate environmental impact. SD delivers it today.",
    body: "Fashion. Sporting goods. Electronics. Furniture. Every durable goods sector is under sustainability pressure. Long-term solutions, circular economy, sustainable materials, supply chain transformation, take years to show results. SD is the bridge. Immediate, measurable conservation impact, starting with the next transaction. When you recommend SD to your members, they get the environmental story they've been looking for. And they get it now, not in five years."
  };

  const projectCopy = {
    headline: "If your project can deliver immediate impact, SD will fund it.",
    body: "SD is not a traditional funder. There is no grant application. If your work is scientifically verified and delivers measurable near-term results, bring it to us. The allocation committee reviews projects on Climate Velocity and Biodiversity Integrity. Projects that pass are funded proportionally to the commerce flowing through SD. Current verified partners: Panthera and Terrasos."
  };

  const closingCopy = {
    headline: "The movement needs more than a mechanism. It needs the people who believe in it.",
    body: "Organizations, celebrities, activists, philanthropists, scientists, journalists, founders. Industry associations, sustainability experts, educators, community leaders. Every voice that promotes this concept accelerates the moment when commerce and conservation become inseparable.",
    cta: "Join the movement."
  };

  return (
    <Layout title={t("meta.faqTitle")} description={t("meta.faqDescription")}>
      <PageHero title={heroTitle} description={heroDescription} carouselSide="right" />

      <section className="sd-section sd-blog-section pt-0">
        <Container className="px-4 px-lg-5">
          <h2 className="text-center sd-section-accent mb-4">{problemCopy.headline}</h2>
          <div className="sd-blog-content mx-auto" style={{ maxWidth: "800px" }}>
            <div className="sd-blog-point mb-3">
              <p className="sd-blog-text"><strong>The gap:</strong> Nature needs $942 billion more per year than it currently receives.</p>
            </div>
            <div className="sd-blog-point mb-3">
              <p className="sd-blog-text"><strong>The strain:</strong> Governments are cutting. Corporate pledges disappear. Conservation professionals are burning out.</p>
            </div>
            <div className="sd-blog-point">
              <p className="sd-blog-text"><strong>The solution:</strong> SD brings a new source of money entirely. Not asking conservation to work harder.</p>
            </div>
          </div>
        </Container>
      </section>

      <section className="sd-section sd-blog-section pt-0">
        <Container className="px-4 px-lg-5">
          <h2 className="text-center sd-section-accent mb-4">{offerCopy.headline}</h2>
          <div className="sd-blog-content mx-auto" style={{ maxWidth: "800px" }}>
            <div className="sd-blog-highlight mb-3">
              <p className="sd-blog-text">Every SD transaction = verified conservation contribution</p>
            </div>
            <p className="sd-blog-text mb-4">Funding scales with commerce, not donor cycles.</p>
            <div className="sd-blog-metrics mb-4">
              <div className="sd-blog-metric">90% to projects</div>
              <div className="sd-blog-metric">10% operations</div>
              <div className="sd-blog-metric">Surplus → conservation</div>
            </div>
            <p className="sd-blog-text mb-3" style={{fontSize: "0.95rem"}}>Transferred within 90 days. Verified. Tracked. Transparent.</p>
          </div>
        </Container>
      </section>

      <section className="sd-section sd-blog-section pt-0">
        <Container className="px-4 px-lg-5">
          <h2 className="text-center sd-section-accent mb-4">{industryCopy.headline}</h2>
          <div className="sd-blog-content mx-auto" style={{ maxWidth: "800px" }}>
            <p className="sd-blog-text mb-3">Every durable goods sector is under sustainability pressure.</p>
            <div className="sd-blog-metrics mb-4">
              <div className="sd-blog-metric">👗 Fashion</div>
              <div className="sd-blog-metric">🏂 Sporting goods</div>
              <div className="sd-blog-metric">📱 Electronics</div>
              <div className="sd-blog-metric">🛋️ Furniture</div>
            </div>
            <p className="sd-blog-text mb-3">Long-term solutions take years. SD is the bridge.</p>
            <div className="sd-blog-highlight">
              <p className="sd-blog-text">Immediate, measurable conservation impact starting today</p>
            </div>
          </div>
          <div className="text-center mt-4">
            <a href="mailto:damian@mandatum.co">
              <button className="sd-cta-btn">Talk to us about your industry</button>
            </a>
          </div>
        </Container>
      </section>

      <section className="sd-section sd-blog-section pt-0">
        <Container className="px-4 px-lg-5">
          <h2 className="text-center sd-section-accent mb-4">{allocationCopy.headline}</h2>
          <div className="sd-blog-content mx-auto" style={{ maxWidth: "800px" }}>
            <p className="sd-blog-text mb-4">Independent committee. Published decisions. Full transparency.</p>
            <div className="sd-faq-criteria mb-4">
              <div className="sd-faq-criterion">
                <h4>Primary</h4>
                <p className="sd-blog-metric-text">🌍 Climate Velocity</p>
                <p className="sd-blog-metric-text">🦁 Biodiversity Integrity</p>
              </div>
              <div className="sd-faq-criterion">
                <h4>Secondary</h4>
                <p className="sd-blog-metric-text">📈 Scalability</p>
                <p className="sd-blog-metric-text">👥 Community Benefit</p>
              </div>
            </div>
            <p className="sd-blog-text mb-3" style={{fontSize: "0.95rem"}}>Seeking representation from leading scientific institutions and frontline practitioners.</p>
          </div>
        </Container>
      </section>

      <section className="sd-section sd-blog-section pt-0">
        <Container className="px-4 px-lg-5">
          <h2 className="text-center sd-section-accent mb-4">{projectCopy.headline}</h2>
          <div className="sd-blog-content mx-auto" style={{ maxWidth: "800px" }}>
            <p className="sd-blog-text mb-3">No grant applications. No lengthy review cycles.</p>
            <div className="sd-blog-highlight mb-4">
              <p className="sd-blog-text">Scientifically verified + Measurable near-term results = Funded</p>
            </div>
            <p className="sd-blog-text mb-3">Evaluated on Climate Velocity and Biodiversity Integrity.</p>
            <p className="sd-blog-text mb-4" style={{fontSize: "0.95rem"}}>Funded proportionally to commerce flowing through SD.</p>
            <div className="sd-blog-partners mb-4">
              <div className="sd-blog-partner">Current: Panthera</div>
              <div className="sd-blog-partner">Current: Terrasos</div>
            </div>
          </div>
          <div className="text-center mt-4">
            <a href="mailto:damian@mandatum.co">
              <button className="sd-cta-btn">Present your project</button>
            </a>
          </div>
        </Container>
      </section>

      <section className="sd-section sd-blog-section sd-blog-cta-section pt-0">
        <Container className="px-4 px-lg-5 text-center">
          <h2 className="sd-section-accent mb-4">{closingCopy.headline}</h2>
          <div className="sd-blog-content mx-auto" style={{ maxWidth: "800px" }}>
            <p className="sd-blog-text mb-4">Conservation organizations. Scientists. Activists. Industry associations.</p>
            <p className="sd-blog-text mb-4">Celebrities. Journalists. Founders. Philanthropists.</p>
            <p className="sd-blog-text mb-4">Educators. Community leaders. Sustainability experts.</p>
            <p className="sd-blog-text mb-4" style={{fontSize: "0.95rem"}}>Every voice that promotes this concept accelerates the moment when commerce and conservation become inseparable.</p>
          </div>
          <div className="mt-4">
            <a href="mailto:damian@mandatum.co">
              <button className="sd-cta-btn">{closingCopy.cta}</button>
            </a>
          </div>
        </Container>
      </section>
    </Layout>
  );
}

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"]))
    }
  };
}
